#!/bin/bash --
#
# Usage:  file-handles [username]
#
# Reports on file handle usage for all processes belonging to
# a particular user.
#
# Copyright (c) 2013, Matthew Kerwin
# All rights reserved.
#
# See attached README.md file for full licensing information.
#

USERNAME=$USER
if [ $# -gt 0 ]; then
	USERNAME=$1
fi

echo "File handles for user $USERNAME"

TOTAL=0
COUNT=0
OVER=0
CRIT=0
UNK=0
REPORT=''
for PID in $(ps -U $USERNAME -u $USERNAME -o pid=) ; do
	nofile=$(ls -l /proc/$PID/fd 2>/dev/null | wc -l)
	soft=$(awk '/Max open files/{print $4}' < /proc/$PID/limits)
	hard=$(awk '/Max open files/{print $5}' < /proc/$PID/limits)
	threshold=$(expr $soft \* 3 / 4)
	COUNT=$(expr $COUNT + 1)
	TOTAL=$(expr $TOTAL + $nofile)
	if [ $nofile -ge $threshold ] ; then
		REPORT="$REPORT- $(ps -p $PID -o user= -o ruser= -o pid= -o ppid=) $nofile $soft $hard $(ps -p $PID -o comm=)\n"
		OVER=$(expr $OVER + 1)
		if [ $nofile -ge $soft ] ; then
			CRIT=$(expr $CRIT + 1)
		fi
	elif [ $nofile -eq 0 ] ; then
		UNK=$(expr $UNK + 1)
	fi
done 2>/dev/null

#if [ $OVER -gt 0 ] ; then
	date +'%Y-%m-%dT%H:%M:%S%z'
	echo "* $OVER of $COUNT processes near soft limit ($CRIT over; $UNK unknown)"
	echo "* $TOTAL measured file handles in total"
	echo -e $REPORT | sort -grk 2
#fi

