#!/bin/bash
#
# A pre-coded `diff` command that displays differences in
# unified format and ANSI colour.
#
# Copyright (c) 2014, Matthew Kerwin
# All rights reserved.
#
# See attached README.md file for full licensing information.
#

ESC=$(echo -e "\033")

diff -u "$@" | sed -r \
	-e 's/^diff .+/'$ESC'[1m&'$ESC'[0m/' \
	-e 's/^([-+])\1+.+/'$ESC'[1m&'$ESC'[0m/' \
	-e 's/^@.+/'$ESC'[36;2m&'$ESC'[0m/' \
	-e 's/^-.*/'$ESC'[1;31;2m&'$ESC'[0m/' \
	-e 's/^\+.*/'$ESC'[1;32;2m&'$ESC'[0m/'

