#!/bin/bash --
#
# Compiles pod from a perl script and displays it like a man page.
#
# Copyright (c) 2013, Matthew Kerwin
# All rights reserved.
#
# See attached README.md file for full licensing information.
#
if [ "$#" -eq 0 ]; then
	echo "Usage:  pod file"
	exit 1
fi
if [ -z "$PAGER" ]; then
	PAGER=/usr/bin/less
fi
/usr/bin/pod2man "$@" | /usr/bin/nroff -man | $PAGER
